### Login with Taavin Tilitoimisto
POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "taavit",
  "password": "sekret"
}

### Login with Tiinan Tukkukauppa
POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "tukkutiina",
  "password": "1234"
}

### Login with Katin Kuljetus
POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "katinkulta",
  "password": "poisalta"
}

### Login with Reiskan Remontti
POST http://localhost:8080/api/login
content-type: application/json

{
  "username": "reiska4ever",
  "password": "4everreiska"
}