### Get all receipts
GET http://localhost:8080/api/receipts


### Create a new receipt
POST http://localhost:8080/api/receipts/addreceipt
content-type: application/json

< ../../docs/single_fake_receipt2.json


### Get a receipt with id
GET http://localhost:8080/api/receipts/34ba08e0-26b4-4d0b-aa0b-ddd37254a612


### Delete a receipt with id
DELETE http://localhost:8080/api/receipts/46e5ee74-9441-4f1d-aae0-a1600a6df345

