@tokenVariable = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtheXR0YWphMiIsImlkIjoiNjFkMjFjMDItMTk2OC00ZTdhLWIxYmUtODA0Njg1OTZiYzFjIiwiaWF0IjoxNjU0MTY1NTM2LCJleHAiOjE2NTQxNjkxMzZ9.6wxGsK7Bfwg7jjvGksfMUH4cUvYtp0ZrjuM9NDCPqfY
@idVariable = 5ec72131-fa79-4d6a-9428-3ecef8f50a2e
@eAddressVariable = did:example:123456789abcdefghi

### Get all receipts
GET http://localhost:8080/api/receipts
Cookie: token={{tokenVariable}}

### Create a new receipt with json content and token
POST http://localhost:8080/api/receipts
Cookie: token={{tokenVariable}}
content-type: application/json

< ../../docs/single_fake_receipt2.json

### Forward an existing receipt to another user
POST http://localhost:8080/api/receipts/forwarded
Cookie: token={{tokenVariable}}
content-type: application/json

{
  "receiptId": "{{idVariable}}",
  "eAddressId": "{{eAddressVariable}}"
}

### Get a receipt with id
GET http://localhost:8080/api/receipts/{{idVariable}}
Cookie: token={{tokenVariable}}

### Delete a receipt with id, this can only be run in development
DELETE http://localhost:8080/api/receipts/{{idVariable}}

### Get all receipts that user has forwarded/sent
GET http://localhost:8080/api/receipts/forwarded
Cookie: token={{tokenVariable}}

### Get all shared receipts to current user from specific user by eAddressId
GET http://localhost:8080/api/receipts/shared/{{eAddressVariable}}
Cookie: token={{tokenVariable}}

### Get name of users and their eAddressId that have shared receipts to current user, also amount of receipts shared
GET http://localhost:8080/api/receipts/shared
Cookie: token={{tokenVariable}}
