### Get all tasks
GET http://localhost:8080/api/tasks


### Create a new task
POST http://localhost:8080/api/tasks/addtask
content-type: application/json

{
"name": "very important task 2", "category": "top-kekret3"
}


### Get a task with id
GET http://localhost:8080/api/tasks/e7736114-9d58-4e9b-a28f-a15dd4ecf04d


### Delete a task with id
DELETE http://localhost:8080/api/tasks/b499f28f-aec7-4092-b9f7-17227f8d7fa1


### Update the name of a task with id
PUT http://localhost:8080/api/tasks/e7736114-9d58-4e9b-a28f-a15dd4ecf04d
content-type: application/json

{
"name": "CHANGED NAME 2"
}