### Get all users
GET http://localhost:8080/api/users


### Create a new user
POST http://localhost:8080/api/users/adduser
content-type: application/json

{
  "username": "kayttaja1",
  "name": "User1",
  "password": "sekret",
  "eAddressId": "did:example:123456789abcdefghi"
}

### Get a user with id
GET http://localhost:8080/api/users/366b9431-e198-4aeb-bc98-5fe2f146f4c6


### Delete a user with id
DELETE http://localhost:8080/api/users/ded44668-33b0-46fa-9208-5101164e4834

